In [41]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [42]:
accident_data = pd.read_csv("accident.csv")
accident_data

,STATE,ST_CASE,VE_TOTAL,VE_FORMS,PVH_INVL,PEDS,PERNOTMVIT,PERMVIT,PERSONS,COUNTY,...,NOT_MIN,ARR_HOUR,ARR_MIN,HOSP_HR,HOSP_MN,CF1,CF2,CF3,FATALS,DRUNK_DR
0,1,10001,1,1,0,0,0,1,1,127,...,99,2,58,88,88,0,0,0,1,1
1,1,10002,1,1,0,0,0,1,1,83,...,99,22,20,88,88,0,0,0,1,0
2,1,10003,1,1,0,0,0,2,2,11,...,99,1,45,99,99,0,0,0,1,1
3,1,10004,1,1,0,0,0,1,1,45,...,99,1,15,88,88,0,0,0,1,1
4,1,10005,2,2,0,0,0,2,2,45,...,99,7,16,88,88,0,0,0,1,0
5,1,10006,1,1,0,0,0,2,2,111,...,99,10,17,99,99,0,0,0,1,0
6,1,10007,1,1,0,0,0,2,2,89,...,99,18,38,99,99,0,0,0,1,0
7,1,10008,1,1,0,1,1,1,1,73,...,99,21,48,99,99,0,0,0,1,0
8,1,10009,1,1,0,0,0,1,1,117,...,99,8,3,88,88,0,0,0,1,0
9,1,10010,2,2,0,0,0,2,2,33,...,99,19,1,99,99,0,0,0,1,0
10,1,10011,2,2,0,0,0,2,2,83,...,99,21,20,88,88,0,0,0,1,0
11,1,10012,3,3,0,0,0,6,6,95,...,99,6,41,99,99,0,0,0,1,0
12,1,10013,1,1,0,0,0,1,1,87,...,88,88,88,88,88,0,0,0,1,1
13,1,10014,1,1,0,0,0,1,1,11,...,99,6,29,88,88,0,0,0,1,1
14,1,10015,1,1,0,0,0,1,1,127,...,99,8,55,88,88,0,0,0,1,0
15,1,10016,2,2,0,0,0,2,2,81,...,99,17,30,99,99,0,0,0,1,0
16,1,10017,1,1,0,0,0,1,1,97,...,99,14,50,99,99,0,0,0,1,0
17,1,10018,1,1,0,0,0,2,2,1,...,99,19,35,99,99,0,0,0,1,1
18,1,10019,1,1,0,0,0,1,1,121,...,88,88,88,88,88,0,0,0,1,0
19,1,10020,2,2,0,0,0,3,3,121,...,99,17,18,99,99,0,0,0,1,0
20,1,10021,2,2,0,0,0,4,4,115,...,99,14,5,99,99,27,0,0,1,0
21,1,10022,1,1,0,0,0,2,2,127,...,99,6,30,99,99,0,0,0,1,0
22,1,10023,1,1,0,0,0,1,1,11,...,99,21,25,88,88,0,0,0,1,1
23,1,10024,1,1,0,0,0,1,1,5,...,99,6,25,99,99,0,0,0,1,0
24,1,10025,1,1,0,0,0,2,2,125,...,88,88,88,88,88,0,0,0,2,1
25,1,10026,1,1,0,0,0,1,1,73,...,99,13,42,88,88,0,0,0,1,0
26,1,10027,2,2,0,0,0,3,3,3,...,99,14,47,99,99,0,0,0,1,0
27,1,10028,1,1,0,0,0,1,1,1,...,99,0,40,88,88,0,0,0,1,1
28,1,10029,1,1,0,0,0,1,1,69,...,99,5,52,88,88,0,0,0,1,0
29,1,10030,2,2,0,0,0,5,5,21,...,99,13,35,88,88,0,0,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32509,56,560101,2,2,0,0,0,2,2,25,...,31,23,46,0,11,0,0,0,1,2
32510,56,560102,1,1,0,0,0,2,2,45,...,36,11,57,12,25,0,0,0,1,1
32511,56,560103,4,1,3,0,0,1,1,25,...,46,18,49,88,88,14,0,0,1,1
32512,56,560104,1,1,0,0,0,2,2,25,...,27,4,41,5,6,0,0,0,1,1
32513,56,560105,1,1,0,0,0,1,1,21,...,43,6,58,88,88,0,0,0,1,0
32514,56,560106,1,1,0,0,0,1,1,9,...,14,0,33,1,3,0,0,0,1,1
32515,56,560107,1,1,0,0,0,1,1,7,...,0,5,37,88,88,0,0,0,1,1
32516,56,560108,1,1,0,0,0,1,1,1,...,4,15,35,88,88,0,0,0,1,1
32517,56,560109,2,2,0,0,0,2,2,25,...,33,15,51,17,14,0,0,0,1,0
32518,56,560110,1,1,0,0,0,2,2,37,...,45,12,6,13,21,0,0,0,1,0
32519,56,560111,1,1,0,0,0,1,1,3,...,15,17,35,18,12,0,0,0,1,1
32520,56,560112,1,1,0,0,0,2,2,13,...,37,7,52,8,28,0,0,0,1,1
32521,56,560113,1,1,0,0,0,1,1,9,...,48,7,7,7,99,0,0,0,1,0
32522,56,560114,1,1,0,0,0,2,2,5,...,46,7,0,7,53,18,0,0,1,0
32523,56,560115,1,1,0,0,0,3,3,13,...,57,11,9,99,99,0,0,0,2,1
32524,56,560116,1,1,0,0,0,2,2,9,...,36,19,45,20,10,20,0,0,2,0
32525,56,560117,1,1,0,0,0,2,2,25,...,99,99,97,99,97,0,0,0,2,1
32526,56,560118,1,1,0,0,0,1,1,31,...,3,8,21,88,88,0,0,0,1,0
32527,56,560119,2,2,0,0,0,2,2,13,...,11,15,20,15,51,0,0,0,1,1
32528,56,560120,1,1,0,0,0,2,2,41,...,28,4,44,5,40,0,0,0,1,1
32529,56,560121,2,2,0,0,0,2,2,25,...,44,17,46,18,3,0,0,0,1,0
32530,56,560122,2,2,0,0,0,2,2,37,...,99,99,99,88,88,0,0,0,1,1
32531,56,560123,1,1,0,1,1,2,2,39,...,54,18,2,88,88,0,0,0,1,0
32532,56,560124,1,1,0,0,0,5,5,33,...,22,0,28,0,42,0,0,0,1,0
32533,56,560125,2,2,0,0,0,2,2,1,...,11,0,28,2,9,0,0,0,1,0
32534,56,560126,2,2,0,0,0,2,2,25,...,29,7,11,88,88,0,0,0,2,0
32535,56,560127,1,1,0,0,0,3,3,21,...,20,22,28,23,36,0,0,0,1,1
32536,56,560128,2,2,0,0,0,2,2,21,...,54,12,2,12,32,0,0,0,1,0
32537,56,560129,2,2,0,0,0,4,4,21,...,12,23,55,0,18,0,0,0,1,0
32538,56,560130,1,1,0,0,0,1,1,33,...,59,22,25,1,16,0,0,0,1,0

In [43]:
accident_data.columns

Index(['STATE', 'ST_CASE', 'VE_TOTAL', 'VE_FORMS', 'PVH_INVL', 'PEDS',
       'PERNOTMVIT', 'PERMVIT', 'PERSONS', 'COUNTY', 'CITY', 'DAY', 'MONTH',
       'YEAR', 'DAY_WEEK', 'HOUR', 'MINUTE', 'NHS', 'RUR_URB', 'FUNC_SYS',
       'RD_OWNER', 'ROUTE', 'TWAY_ID', 'TWAY_ID2', 'MILEPT', 'LATITUDE',
       'LONGITUD', 'SP_JUR', 'HARM_EV', 'MAN_COLL', 'RELJCT1', 'RELJCT2',
       'TYP_INT', 'WRK_ZONE', 'REL_ROAD', 'LGT_COND', 'WEATHER1', 'WEATHER2',
       'WEATHER', 'SCH_BUS', 'RAIL', 'NOT_HOUR', 'NOT_MIN', 'ARR_HOUR',
       'ARR_MIN', 'HOSP_HR', 'HOSP_MN', 'CF1', 'CF2', 'CF3', 'FATALS',
       'DRUNK_DR'],
      dtype='object')

In [44]:
State_Deaths = accident_data.loc[:, ["STATE", "HARM_EV", "FATALS"]]
State_Deaths = State_Deaths.set_index("STATE")

State_Deaths.head()

       HARM_EV  FATALS
STATE
1           35       1
1           34       1
1           42       1
1           53       1
1           12       1

In [45]:
CO_Deaths = State_Deaths.loc[6,["HARM_EV", "FATALS"]]

CO_Deaths

       HARM_EV  FATALS
STATE
6           24       1
6           12       2
6            8       1
6           12       1
6            8       1
6           43       1
6           12       1
6            1       2
6           24       1
6            8       1
6           12       1
6            8       1
6            8       1
6            8       1
6           12       1
6            8       1
6            8       1
6           15       1
6            8       1
6           12       1
6           30       1
6            1       1
6            8       1
6           12       2
6           42       2
6           12       1
6           17       1
6           52       1
6            1       1
6           12       1
...        ...     ...
6           12       1
6           12       4
6           39       1
6            8       1
6            9       1
6            8       1
6            8       1
6           35       1
6            8       1
6           12       1
6           12       1
6           12       1
6           33       2
6           12       1
6            8       1
6           12       1
6            1       1
6            8       1
6            8       1
6           39       1
6           33       1
6            8       1
6            8       1
6            8       1
6           12       1
6            8       1
6            8       1
6            8       1
6           12       1
6           35       1

[3123 rows x 2 columns]

In [46]:
top_causes = CO_Deaths.sort_values(["HARM_EV"], ascending=False)
top_causes = top_causes.drop_duplicates()
top_causes.head(5)

       HARM_EV  FATALS
STATE
6           73       1
6           72       1
6           59       1
6           59       2
6           58       1

In [56]:

top_causes.plt.bar(x_axis, HARM_EV, color='r', alpha=0.5, align="center")

AttributeError: 'DataFrame' object has no attribute 'plt'

In [54]:
HARM_EV_data = top_causes["HARM_EV"].value_counts()
HARM_EV_data
FATALS_data = top_causes["FATALS"].value_counts()
FATALS_data

1    42
2    24
3     5
4     2
5     1
Name: FATALS, dtype: int64